In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Datasets/logistic regression dataset-Social_Network_Ads.csv')

In [3]:
df.head()

,User ID,Gender,Age,EstimatedSalary,Purchased
0,15624510,Male,19,19000,0
1,15810944,Male,35,20000,0
2,15668575,Female,26,43000,0
3,15603246,Female,27,57000,0
4,15804002,Male,19,76000,0


In [4]:
#basic data analysis before the forecast

In [5]:
#1. See the type of values Gender has in the data frame
df['Gender'].unique()

array(['Male', 'Female'], dtype=object)

In [6]:
#2. Convert 'Male' -> 1 and 'Female' -> 0
df.replace({'Male':1, 'Female':0}, inplace=True)

C:\Users\prajw\AppData\Local\Temp\ipykernel_14200\2154375244.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace({'Male':1, 'Female':0}, inplace=True)


In [7]:
df.head()

,User ID,Gender,Age,EstimatedSalary,Purchased
0,15624510,1,19,19000,0
1,15810944,1,35,20000,0
2,15668575,0,26,43000,0
3,15603246,0,27,57000,0
4,15804002,1,19,76000,0


In [8]:
#3. to check the co-relation between User Id and Purchased. Assuming there is no co-relation
df.corr()

,User ID,Gender,Age,EstimatedSalary,Purchased
User ID,1.000000,-0.025249,-0.000721,0.071097,0.007120
Gender,-0.025249,1.000000,-0.073741,-0.060435,-0.042469
Age,-0.000721,-0.073741,1.000000,0.155238,0.622454
EstimatedSalary,0.071097,-0.060435,0.155238,1.000000,0.362083
Purchased,0.007120,-0.042469,0.622454,0.362083,1.000000


In [9]:
df['User ID'].value_counts()

User ID
15707634    1
15715622    1
15670615    1
15683758    1
15749381    1
           ..
15804002    1
15603246    1
15668575    1
15810944    1
15624510    1
Name: count, Length: 400, dtype: int64

In [8]:
#since the user ids are unique, independent and not contributing to the output, dropping the column
df = df.drop('User ID', axis=1)

In [11]:
df.head()

,Gender,Age,EstimatedSalary,Purchased
0,1,19,19000,0
1,1,35,20000,0
2,0,26,43000,0
3,0,27,57000,0
4,1,19,76000,0


In [12]:
# supervised learning

In [9]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [26]:
X = df.iloc[:,0:-1]
y = df.iloc[:,-1]

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [16]:
y_train.shape

(320,)

In [17]:
model = LogisticRegression()

In [19]:
model.fit(X_train, y_train)

C:\Users\prajw\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [20]:
y_pred = model.predict(X_test)

In [21]:
y_pred

array([0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0])

In [22]:
y_test.to_numpy()

array([0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0])

In [37]:
#evaluation metrics for classification problem
from sklearn import metrics

In [24]:
print("Metrics using OLS:")
print("Accuracy", metrics.accuracy_score(y_pred, y_test))
print("F1:",metrics.f1_score(y_pred, y_test))
print("Confusion matrix:", metrics.confusion_matrix(y_pred, y_test))

Metrics using OLS:
Accuracy 0.8375
F1: 0.7450980392156863
Confusion matrix: [[48  3]
 [10 19]]


In [25]:
#Building a neural network for the same problem

In [11]:
import torch
import torch.nn as nn
from sklearn.preprocessing import StandardScaler

In [12]:
#normalize the data
scaler = StandardScaler()

In [27]:
X = X.values
y = y.values

In [28]:
X = scaler.fit_transform(X)
#y = scaler.fit_transform(y)

In [29]:
X = torch.tensor(X.astype(np.float32))
y = torch.tensor(y, dtype=torch.float32).reshape(-1,1)

In [30]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [49]:
class NeuralNetwork(nn.Module):
    def __init__(self):
        super(NeuralNetwork, self).__init__()
        #self.m = nn.Parameter(torch.zeros(3,1)) # set of weights
        #self.c = nn.Parameter(torch.zeros(1,1)) # 1 bias in the form of a tensor
        self.linear = nn.Linear(3,1)
        
    def forward(self, x):
        #y = (x@self.m + self.c)
        y = self.linear(x)
        return y

    # first draft: I am not including the sigmoid function here as part of the learning. Because- let the algorithm learn
    # and sigmoid operation can be included later

In [70]:
regression = NeuralNetwork()
epoch = 400
optimizer = torch.optim.SGD(regression.parameters(), lr=0.01)

In [71]:
for i in range(epoch):
    y_pred = regression(X_train)
    #y_prob = torch.sigmoid(y_pred)

    criterion = nn.BCEWithLogitsLoss()
    loss = criterion(y_pred, y_train.float())

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if (i%50 == 0):
        #print(i, loss, regression.m.grad, regression.c.grad)
        print(i, loss)

0 tensor(1.0099, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)
50 tensor(0.8796, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)
100 tensor(0.7773, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)
150 tensor(0.6989, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)
200 tensor(0.6394, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)
250 tensor(0.5940, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)
300 tensor(0.5590, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)
350 tensor(0.5316, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)


In [72]:
y_pred = regression(X_test)
y_pred_prob = torch.sigmoid(y_pred)

In [73]:
y_res = torch.where(y_pred_prob >= 0.5, 1.0, 0.0)

In [117]:
y_res.numpy().reshape(1,-1)

array([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 0.,
        1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 0.,
        1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],
      dtype=float32)

In [118]:
y_test.numpy().reshape(1,-1)

array([[0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0.,
        0., 1., 0., 1., 1., 1., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0.,
        0., 1., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 1., 0.,
        1., 0., 0., 1., 0., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 0.,
        1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.]],
      dtype=float32)

In [74]:
print("Metrics using Neural networks:")
print("Accuracy", metrics.accuracy_score(y_res, y_test))
print("F1:",metrics.f1_score(y_res, y_test))
print("Confusion matrix:", metrics.confusion_matrix(y_res, y_test))

Metrics using Neural networks:
Accuracy 0.8875
F1: 0.8235294117647058
Confusion matrix: [[50  7]
 [ 2 21]]
